spring:
  application:
    name: recetalia-api
  server:
    port: 8080
  # JPA
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Database Configuration
  datasource:
    url: jdbc:mysql://143.110.212.167:3306/recetali_receta
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: recetali_receuser
    password: RecePass2021

  # DNMA data source configuration
  dnma:
    datasource:
      url: jdbc:mysql://143.110.212.167:3306/recetali_dnma
      username: recetali_receuser
      password: RecePass2021

jwt:
  secret: nSgDQMoPRNrLrCHZj6aWMEkJ6TfZAHYbGAefyLE2MlF3+zRoRJdJrYdgl8tgpvWHzOlPYz4Ly/KTFCayEImjmw==

logging:
  level:
    org.springframework.security.oauth2.server.resource: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    io.jsonwebtoken: DEBUG